"""verification documents overhaul

Revision ID: 0f709afc164b
Revises: 3f8a56eeefd0
Create Date: 2026-06-13 00:43:27.584075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f709afc164b'
down_revision = '3f8a56eeefd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('verification_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_status', sa.Enum('pending', 'approved', 'rejected', name='docstatus'), nullable=False))
        batch_op.add_column(sa.Column('rejection_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('rejection_comment')
        batch_op.drop_column('doc_status')
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('rejection_comment')

    # ### end Alembic commands ###
