"""add contact fields and pending_verification status to business

Revision ID: 3f8a56eeefd0
Revises: ccb819378def
Create Date: 2026-06-13 00:35:14.132679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f8a56eeefd0'
down_revision = 'ccb819378def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'verified', 'rejected', 'suspended'),
               type_=sa.Enum('pending_verification', 'verified', 'rejected', 'suspended', name='businessstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending_verification', 'verified', 'rejected', 'suspended', name='businessstatus'),
               type_=mysql.ENUM('pending', 'verified', 'rejected', 'suspended'),
               existing_nullable=False)
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')

    # ### end Alembic commands ###
