"""add sort_order to product_images

Revision ID: 7816ba616d6c
Revises: 0f709afc164b
Create Date: 2026-06-13 00:50:35.026430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7816ba616d6c'
down_revision = '0f709afc164b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
